export enum UserActionTypes {
  FETCH_USERS = "FETCH_USERS",
  FETCH_USERS_ONSUCCESS = "FETCH_USERS_ONSUCCESS",
  FETCH_USERS_ERROR = "FETCH_USERS_ERROR",
}

export enum AlbumsActionTypes {
  FETCH_ALBUMS = "FETCH_ALBUMS",
  FETCH_ALBUMS_ONSUCCESS = "FETCH_ALBUMS_ONSUCCESS",
  FETCH_ALBUMS_ERROR = "FETCH_ALBUMS_ERROR",
  SET_PAGE = "SET_PAGE"
}